name: AWS Resource Cleanup

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install AWS SDK for Python (Boto3)
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Run Python cleanup script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          python script.py  # Ensure this script is in the repository
          python s3_cleanup.py


